name: "Style check"
description: "Style check using clang-format"

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        # We only make check, not changes
        # Use the find command with the variable
        PROJECT_PATH=$(pwd)

        echo $PROJECT_PATH

        # It finds all the source files (*.cpp, *.hpp, *.h, *.c) in the src, include, and lib directories of the project and saves them in a variable called SOURCE_FILES
        # *tr* command takes the output of the *find* command and it replaces the 'new line' characters with withespace
        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/lib -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt

        # *clang format* formats the source code files from *SOURCE_FILES* an sends the output to the env var *CLANG_COMMAND* and to the file specified in *ERROR_FILE_FLAG*
        CLANG_COMMAND=$(clang-format -i $SOURCE_FILES) > ${ERROR_FILE_FLAG}

        echo "Running: clang-format -i $SOURCE_FILES"

        # It checks if the errors' file  has a size higgher than 0 (if there are formatting errors). If it's true it exits the execution with the error code, otherwise it finishes properly
        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: There are some files that are not formatted correctly"
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Clang-format errors!!!
        path: $PROJECT_PATH/clang-format_errors.txt
        retention-days: 1
